blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AliiiBenn/complete-electron-template/tree/main/docs
    about: Check the docs folder for project documentation
  - name: Discussions
    url: https://github.com/AliiiBenn/complete-electron-template/discussions
    about: Use GitHub Discussions for questions and feature ideas